### ISSUE TITLE
Validation bubble height should be the same as the input

### ISSUE THREAD

**Issue by ndevalle** [mercadolibre/chico#1135]
``` css
.ch-bubble {
    padding: 5px 5px 5px 25px;
}

.ch-bubble .ch-icon-remove-sign {
    top: 2px;
}


/**
 * Top alignment
 */
.ch-cone[data-side=right][data-align=top] .ch-popover-content:after,
.ch-cone[data-side=left][data-align=top] .ch-popover-content:after {
    top: 8px;
}

.ch-cone[data-side=right][data-align=top] .ch-popover-content:before,
.ch-cone[data-side=left][data-align=top] .ch-popover-content:before {
    top: 7px;
}
```
