### ISSUE TITLE
Link-buttons doesn't inherit text color

### ISSUE THREAD

**Issue by llinares** [mercadolibre/chico#1204]
Be specific on link-button colors:

```css
a.ch-btn,
a.ch-btn:focus,
a.ch-btn:visited {
    color: #fff;
}

a.ch-btn-skin,
a.ch-btn-skin:focus,
a.ch-btn-skin:visited {
    color: #476274;
}
```
