### ISSUE TITLE
Is the `padding` in the `body` really necessary?

### ISSUE THREAD

**Issue by battaglr** [mercadolibre/chico#1224]
In `shared/reset.css` que can see the following:

```css
body {
  padding: 0 10px; /* Prevent layout "sticking" to the edge of the browser */
}
```

I don't quite get why Chico should assign a `padding` to the `body` —every browsers sets a default of `0`. Why is "prevent layout 'sticking' to the edge of the browser" a bad thing that we need to prevent with that line?
