### ISSUE TITLE
Don't reset styles on input radio and checkbox.

### ISSUE THREAD

**Issue by Patriciamartins** [mercadolibre/chico#914]
Seteamos css para input radios en safari. Pero en realidad podrían dejar el default del browser. 
Slds

``` css
.ch-list-options input[type="radio"]  {
    border: 1px solid #999;
    padding: 0;
    background-color:#999;
}
```
